### ISSUE TITLE
Mouse Wheel doesn't work when taking something from Stone Cutter

### ISSUE THREAD

**Issue by VincyZed** [YaLTeR/MouseTweaks#151]
As the title says, when scrolling on the resulting block in the Stone Cutter, nothing happens.

**Comment by YaLTeR** [comment]
This is because the stone cutter's scrolling UI steals the wheel inputs. In Minecraft you can scroll a scrolling UI from any position on screen, not just when hovering the scrolling slots.

I didn't want to do any kind of major interference to work around that to avoid breaking any mod compatibility.
