### ISSUE TITLE
Does not work in dev environment

### ISSUE THREAD

**Issue by Jkosio23** [YaLTeR/MouseTweaks#18]
Whenever I try to build my dev environment with mouse tweaks its calling for an obfuscated class, which, when in a dev environment, is obviously deobfuscated and gets its proper name.

**Comment by YaLTeR** [comment]
So the issue here is that I need the final .jar to be obfuscated for it to work on a LiteLoader-only setup (no Forge) because LiteLoader doesn't do deobfuscation. I'm not sure if there's a way to set up `build.gradle` to additionally output a deobfuscated .jar, some help would be welcome with this.

**Comment by mezz** [comment]
Building a deobfuscated jar is not really a good choice because it will fail when the mcp mappings between the projects are not exactly the same.

I think setting this to "searge" should let it build into an obfuscated format that will work because Forge can automatically deobfuscate it in the dev environment:
https://github.com/YaLTeR/MouseTweaks/blob/ad6f36c544e5969289250f2327a1f76eecc299ab/build.gradle#L48
I am not sure how to build for both types of obfuscated environments using MixinGradle though, maybe someone who is more knowledgeable about mixins will know.

**Comment by YaLTeR** [comment]
Since 1.13 I changed the build files to do the standard things for Forge and Fabric so hopefully this is no longer an issue.
