### ISSUE TITLE
1.14.4 Client crash

### ISSUE THREAD

**Issue by Wissi** [YaLTeR/MouseTweaks#28]
Awesome must have mod, thank you very much.

We have been using it without issues until recently it is crashing our clients when using a right mouse button on certain crafting stations.

Full crash log [here](https://gist.github.com/Wissi/08b2f734c592040fa7d579eff292c28f).

Hope it helps and is a simple fix.

Using: 
Forge 2.8.1.79
MouseTweaks-2.12-mc1.14.4

**Comment by YaLTeR** [comment]
Thanks for the report!

Could you explain in detail what exactly you are doing in the crafting station to cause a crash? Perhaps record a video if that's not too much effort.

Also I know it says "report to them NOT Crafting Station" there in the stack trace, but could you report it to Crafting Station too and link the issue? The way Mouse Tweaks works (`handleMouseClick()`) should in theory not be any different from the player clicking a mouse, and a number issues reported with that kind of crash have been caused by the container-providing mods' behavior, not MT.

**Comment by Wissi** [comment]
Yeah have reported it to them as well and I guess they have had the issue before and opted to place that line of code to "not' report it to them.

To reproduce it:
Place any amount of blocks in crafting station (their mod type - not vanilla), then right clicking on it to removes 1/2 of it and crashes.
Tried on vanilla crafting table and other mods crafitng tables, had no issue, no crashing. 

Hope it helps get intermod use working, Thanks.

Link to the report on their end is [here](https://github.com/Tfarcenim/crafting-station/issues/33).

**Comment by Tfarcenim** [comment]
It's not mousetweaks but rather corial pillar accessing a slot outside of the inventory

**Comment by Wissi** [comment]
Thank you so much, I have reported to Corail as well.

Thread [here](https://github.com/Corail31/corail-pillar/issues/26#issue-516925257).

**Comment by Wissi** [comment]
Well thanks for all your Help. 
It seems it's a well known bug in code and is waiting to be fixed by another mod.

We love  your mod and is working flawlessly so far. 
If we run into nay issues, we'll let you know.

Thanks.

**Comment by YaLTeR** [comment]
Awesome!
