### ISSUE TITLE
1.5.2 Modpack Crash (F3 Screen/Profiler)

### ISSUE THREAD

**Issue by jadenquinn** [YaLTeR/MouseTweaks#41]
I just remembered I should probably post here instead of the Curseforge Mod Page:

Getting a crash on my 1.5.2 Modpack, and I just figured out it was Mouse Tweaks erroring: https://docs.google.com/document/d/1lD2s4kCUxdOe44UG7xkcp1cE98tMDrOS9eDt2lEvqp8/edit?usp=sharing
All I did was try to bring up the F3 Screen or Profiler.

Yes I tried pastebin, for some reason it deemed the logs "offensive". I deem that stupid.

Thanks!
-jaden-

**Comment by YaLTeR** [comment]
The stack trace is:
```
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.remove(Unknown Source)
    at net.minecraft.profiler.Profiler.func_76319_b(Profiler.java:103)
    at MouseTweaks.ProfilerCustom.func_76319_b(ProfilerCustom.java:37)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:877)
    at net.minecraft.client.Minecraft.run(Minecraft.java:760)
    at java.lang.Thread.run(Unknown Source)
```

Mouse Tweaks for 1.5.2 [overrides the profiler](https://github.com/YaLTeR/MouseTweaks/blob/b4d3f241f14b5ded016c49ee3ecd72caf5e015d3/MouseTweaks/ProfilerCustom.java#L20) in order to call its update function. However, it then calls right back into the original profiler without any changes. This leads me to believe that the crash is unrelated to Mouse Tweaks, but I really don't know.

Could you try with just Mouse Tweaks or with Mouse Tweaks removed to see if maybe some other mod is responsible?

**Comment by jadenquinn** [comment]
This didn't used to happen, and I seem to remember adding Eternal Frost (If not more) and it breaking like this, but I didn't realize it had anything to do with Mouse Tweaks.

I'll post a pack.zip for MultiMC.

**Comment by jadenquinn** [comment]
Importable MultiMC Instance: https://drive.google.com/file/d/106bJ6RuDaQZcOZq92rGv1Tsv_ZvV-bYb/view?usp=sharing

**Comment by YaLTeR** [comment]
Could you try with your current modpack but without Mouse Tweaks and see if the crash still happens?

**Comment by jadenquinn** [comment]
It did. Mouse Tweaks just vanishes from the log.

**Comment by YaLTeR** [comment]
So then this is not a mouse tweaks issue?

**Comment by jadenquinn** [comment]
Apparently not.
