### ISSUE TITLE
Upload 1.18-2.22 Forge to Curseforge

### ISSUE THREAD

**Issue by itsdinkd** [YaLTeR/MouseTweaks#67]
Hello, AQM3 modpack dev here.

Can you upload 1.18-2.22 which is on modrinth, to curseforge? this way I can update it in my modpack and release the update?

thanks!

**Comment by YaLTeR** [comment]
It's already on CurseForge: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files

The Forge version is at 2.21 because there were no changes to it in 2.22. I uploaded it on modrinth just because I had the JARs downloaded. Other than the version number there's no difference between Forge 2.21 and 2.22.
