### ISSUE TITLE
Please update to the latest version of forge 1.19 because the mod does not work 

### ISSUE THREAD

**Issue by papillo12** [YaLTeR/MouseTweaks#79]
Well, a few days ago forge updated and made your mod unusable, so hopefully you can update it soon.

**Comment by YaLTeR** [comment]
Fixed in https://github.com/YaLTeR/MouseTweaks/commit/2c10082a584194d8ab7731a7d8b3963cead46c34, https://github.com/YaLTeR/MouseTweaks/commit/2fe9b08dc00878a40bb75becb092afaeb2cbae75. Please download Mouse Tweaks 2.23 on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files) or [modrinth](https://modrinth.com/mod/mouse-tweaks/versions).
